apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"kind":"Image","apiVersion":"kpack.io/v1alpha1","metadata":{"name":"spring-petclinic-kubectl","namespace":"default","creationTimestamp":null},"spec":{"tag":"harbor-demo.ryanbaker.io/demo-tbs/spring-petclinic","builder":{"kind":"ClusterBuilder","name":"base"},"serviceAccount":"default","source":{"git":{"url":"https://github.com/ryan-a-baker/spring-petclinic.git","revision":"main"}},"build":{"resources":{}}},"status":{}}'
  creationTimestamp: null
  name: spring-petclinic-kubectl
  namespace: default
spec:
  build:
    resources: {}
  builder:
    kind: ClusterBuilder
    name: base
  serviceAccount: default
  source:
    git:
      revision: main
      url: https://github.com/ryan-a-baker/spring-petclinic.git
  tag: harbor-demo.ryanbaker.io/demo-tbs/spring-petclinic
status: {}
